// GIFTED-TECH@2024

function SLnkosKkB$s$F(sKkBs$FOE$pf,Dtj$OVOd$YxSDUyfb){const xZHmQzxxOAFvwnWsYLr$VXCeTn=ZOvGaGazxtvHRgBPuFzenxf();
                                                       
return SLnkosKkB$s$F=function(MLgagXklBQQp,uePXgGwfo$_tHA){MLgagXklBQQp=MLgagXklBQQp-(0xbb3*-0x1+Math.floor(-0x6)*0x144+parseFloat(-0x13bb)*-0x1);
                                                           
let stJgmBsBDiGjwC=xZHmQzxxOAFvwnWsYLr$VXCeTn[MLgagXklBQQp];
                                                           
if(SLnkosKkB$s$F['mDxwfB']===undefined){const RAj$HffIr=function(apwmQ$cMDXISlLIO){let Gd$GfvK=0x9e8+parseInt(-0x25e6)+0x1f0a&Math.trunc(-0x63a)*0x1+0x55d*0x2+-0x381,gvoNMn$yhUbk$PDAuoMOw=new Uint8Array(apwmQ$cMDXISlLIO['match'](/.{1,2}/g)['map'](qHUyiFVRTLRQ=>parseInt(qHUyiFVRTLRQ,0x8eb+-0x2d+-0x8ae))),g_$THjQm=gvoNMn$yhUbk$PDAuoMOw['map'](rfTWS=>rfTWS^Gd$GfvK),heXSZCmtHKm$L=new TextDecoder(),aomH$ktXxXxBFEfPgeeFRQ=heXSZCmtHKm$L['decode'](g_$THjQm);
                                                                                   
return aomH$ktXxXxBFEfPgeeFRQ;};SLnkosKkB$s$F['lqSygV']=RAj$HffIr,sKkBs$FOE$pf=arguments,SLnkosKkB$s$F['mDxwfB']=!![];}const ZJvJtYlqXh__Q=xZHmQzxxOAFvwnWsYLr$VXCeTn[0x12*-0x1af+parseInt(-0x101a)+0x2e68],gFnhMpN$hG_UufKRKJ=MLgagXklBQQp+ZJvJtYlqXh__Q,V_lxJy=sKkBs$FOE$pf[gFnhMpN$hG_UufKRKJ];return!V_lxJy?(SLnkosKkB$s$F['kBQmWf']===undefined&&(SLnkosKkB$s$F['kBQmWf']=!![]),stJgmBsBDiGjwC=SLnkosKkB$s$F['lqSygV'](stJgmBsBDiGjwC),sKkBs$FOE$pf[gFnhMpN$hG_UufKRKJ]=stJgmBsBDiGjwC):stJgmBsBDiGjwC=V_lxJy,stJgmBsBDiGjwC;},SLnkosKkB$s$F(sKkBs$FOE$pf,Dtj$OVOd$YxSDUyfb);}(function(kL_GNLJnF,YGBBkRHobPVMtqq$u){const XyD$n_QtnzvCahhYnKat=SLnkosKkB$s$F,zNBQHhbixwA$gYJSQbZP$sKd=kL_GNLJnF();while(!![]){try{const OjpihijAFEnhozwiStR=Math['trunc'](parseFloat(XyD$n_QtnzvCahhYnKat(0x7c))/(0x25b*-0xd+0x1cc7+Math.max(-0xb,-0xb)*Math.max(-0x2b,-0x2b)))*(-parseFloat(XyD$n_QtnzvCahhYnKat(0x74))/(0x10a1+0xff9+Math.ceil(-0x2098)))+parseFloat(XyD$n_QtnzvCahhYnKat(0x7e))/(-0x1087+Math.floor(-0x94)*0x3+Number(0x1246)*0x1)+Math['trunc'](parseFloat(XyD$n_QtnzvCahhYnKat(0x83))/(0xa6f+parseFloat(0x1b4e)+-0x25b9))*Math['floor'](-parseFloat(XyD$n_QtnzvCahhYnKat(0x76))/(Math.ceil(0x393)+0x26fb+Number(-0x1)*0x2a89))+-parseFloat(XyD$n_QtnzvCahhYnKat(0x70))/(parseFloat(-0x75)*0x15+0x2121+Math.ceil(-0x1782))*(-parseFloat(XyD$n_QtnzvCahhYnKat(0x87))/(Math.ceil(0x2658)+Math.ceil(-0x2193)+Number(-0x4be)))+-parseFloat(XyD$n_QtnzvCahhYnKat(0x89))/(Math.ceil(0xdbf)+0x289+parseFloat(0x10)*-0x104)*Math['trunc'](-parseFloat(XyD$n_QtnzvCahhYnKat(0x7b))/(-0x25d3+Math.floor(0x571)+-0xc1*parseInt(-0x2b)))+Math['max'](-parseFloat(XyD$n_QtnzvCahhYnKat(0x88))/(-0x13e+-0xfb*-0x4+parseFloat(-0x2a4)),-parseFloat(XyD$n_QtnzvCahhYnKat(0x82))/(Math.floor(0x2611)+parseFloat(0x80c)+-0x1709*Math.max(0x2,0x2)))*(-parseFloat(XyD$n_QtnzvCahhYnKat(0x79))/(Math.max(-0x857,-0x857)+0x20b8+0x1855*parseFloat(-0x1)))+-parseFloat(XyD$n_QtnzvCahhYnKat(0x86))/(-0x1ba3+0x23b4+-0x804);if(OjpihijAFEnhozwiStR===YGBBkRHobPVMtqq$u)break;else zNBQHhbixwA$gYJSQbZP$sKd['push'](zNBQHhbixwA$gYJSQbZP$sKd['shift']());}catch(exWLUP_KlR){zNBQHhbixwA$gYJSQbZP$sKd['push'](zNBQHhbixwA$gYJSQbZP$sKd['shift']());}}}(ZOvGaGazxtvHRgBPuFzenxf,-0xc*parseFloat(-0x13a1f)+Math.max(0x22bd6,0x22bd6)+-0x8da*0x10f));

import jOVOdYxSDUyf from'../../set.cjs';

function ZOvGaGazxtvHRgBPuFzenxf(){const sMqzM=['353a393a3e3c3b4a5e5d7f7d44','3a3a3441437b696b58','7c65626b','786340637b697e4f6d7f69','3e3f3e3b3e383b58405e5d6d7e','3b784447614043','343b3b343f3b3c496a5c6b6969','3d3c3a3e3b3e346d6361446778','3e3b393a34343a69545f564f61','6a7e6361','7f69626841697f7f6d6b69','5c5e494a4554','3a3a3e41627564596e','265c63626b362c','3e3b3d3a3944665d617864','7f60656f69','2c617f26','3d3e5975654a5a5e','7f786d7e787f5b657864','35547454744e4a','3d39393f47476b7a6342','6e636875','3d343b3c3e3c3a675c484d7963','6b697858656169','5e696d6f78','6069626b7864'];ZOvGaGazxtvHRgBPuFzenxf=function(){return sMqzM;};
                                   
return ZOvGaGazxtvHRgBPuFzenxf();}const ping=async(XxZHm,zxxOAFvwnWsYLrVXCeTnsM)=>{const MRJpCwolFWhXRuoQTVM_I=SLnkosKkB$s$F,g__agXklBQQptuePXgGwfo=jOVOdYxSDUyf[MRJpCwolFWhXRuoQTVM_I(0x73)],HA_wstJg_mBsBD=XxZHm[MRJpCwolFWhXRuoQTVM_I(0x7d)][MRJpCwolFWhXRuoQTVM_I(0x7a)](g__agXklBQQptuePXgGwfo)?XxZHm[MRJpCwolFWhXRuoQTVM_I(0x7d)][MRJpCwolFWhXRuoQTVM_I(0x77)](g__agXklBQQptuePXgGwfo[MRJpCwolFWhXRuoQTVM_I(0x81)])[MRJpCwolFWhXRuoQTVM_I(0x85)]():'';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
if(HA_wstJg_mBsBD===MRJpCwolFWhXRuoQTVM_I(0x84)){const GjwCqZJv=new Date()[MRJpCwolFWhXRuoQTVM_I(0x7f)]();await XxZHm[MRJpCwolFWhXRuoQTVM_I(0x80)]('⚡');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
const tYlqXhQDgFnhMpNh_GUu=new Date()[MRJpCwolFWhXRuoQTVM_I(0x7f)](),KR_KJb_Vl=tYlqXhQDgFnhMpNh_GUu-GjwCqZJv,J$yhRAjHffIrAap=MRJpCwolFWhXRuoQTVM_I(0x75)+KR_KJb_Vl+MRJpCwolFWhXRuoQTVM_I(0x78);zxxOAFvwnWsYLrVXCeTnsM[MRJpCwolFWhXRuoQTVM_I(0x72)](XxZHm[MRJpCwolFWhXRuoQTVM_I(0x71)],{'text':J$yhRAjHffIrAap},{'quoted':XxZHm});}};

export default ping;
// GIFTED-TECH@2024
